Repository Arquisoft/wichat_es1c, pull requests merged in 2025-03, with the labels that each got.

#35 [DOC] Actualización capítulos 9 y 11 de la documentación
  docs/src/09_architecture_decisions.adoc
  docs/src/11_technical_risks.adoc
Labels: 📄 documentation

#45 Refactorización GameService
  gameservice/.dockerignore
  gameservice/Dockerfile
  gameservice/README.md
  gameservice/data/questions-templates.json
  gameservice/models/question-model.js
  gameservice/models/template-model.js
  gameservice/package-lock.json
  gameservice/package.json
  gameservice/questions-service.js
  gatewayservice/gateway-service.js
  webapp/src/App.js
  webapp/src/components/Game.js
Labels: 💡 enhancement, ⚙ development

#51 Arreglado bug enlace a registro en /home y en /game
  webapp/src/App.js
  webapp/src/components/Chatbot.js
  webapp/src/components/Game.js
  webapp/src/components/OptionsDropdown.js
  webapp/src/logo.svg
Labels: 🕷 bug, ⚙ development, 🚀 improvement

#58 Optimización del juego.
  webapp/src/components/Game.js
Labels: 🚀 improvement

#59 [STYLE] Añadidos cambios de fondo aleatorio para la aplicación
  webapp/src/App.js
Labels: ⚙ development, ✨ visual enhancement

#60 Creada página faqs con algunas preguntas.
  webapp/src/App.js
  webapp/src/components/Faq.js
  webapp/src/components/Game.js
  webapp/src/components/OptionsDropdown.js
Labels: 💡 enhancement, ⚙ development

#63 Se ha realizado la corrección de la documentación
  docs/src/02_architecture_constraints.adoc
  docs/src/12_glossary.adoc
Labels: 📄 documentation

#64 Solucion LLM
  webapp/backend/gatewayservice/server.js
  webapp/backend/llmservice/chatbot.js
Labels: ⚙ development

#66 Nueva funcionalidad FAQ y arreglo de Game
  webapp/src/components/Faq.js
  webapp/src/components/Game.js
Labels: ⚙ development, 🚀 improvement

#67 [STYLE] Añadido Css de FAQ, de Game y de Home.
  webapp/src/FAQ.css
  webapp/src/Game.css
  webapp/src/components/Faq.js
  webapp/src/components/Game.js
  webapp/src/components/Home.js
Labels: ⚙ development, ✨ visual enhancement

#68 Solución bug guardado de resultado en la base de datos
  webapp/src/components/Game.js
Labels: 🚀 improvement

#91 Cambios en registro de datos de partida en la base de datos.
  webapp/backend/gameservice/models/score-model.js
  webapp/backend/gameservice/questions-service.js
  webapp/src/App.js
  webapp/src/components/Game.js
  webapp/src/components/OptionsDropdown.js
  webapp/src/components/Ranking.js
Labels: ⚙ development

#98 Ranking personal y cambios en el home
  userservice/register.js
  webapp/package-lock.json
  webapp/package.json
  webapp/src/components/Game.js
  webapp/src/components/Home.js
  webapp/src/components/PersonalRanking.js
  webapp/src/components/Ranking.js
Labels: ⚙ development

#100 [DEV] Cambios en el fondo, el css de Login e imágenes varias. Establecido el estilo general de la página y barra de navegación básica.
  docs/images/10-árbol.png
  webapp/public/FondoWichat.png
  webapp/public/LogoWichat.gif
  webapp/src/App.js
  webapp/src/Login.css
  webapp/src/Register.css
  webapp/src/components/Home.js
  webapp/src/components/Login.js
  webapp/src/components/OptionsDropdown.js
  webapp/src/components/Register.js
Labels: ⚙ development, ✨ visual enhancement

#103 Primera versión del user data
  gameservice/questions-service.js
  gatewayservice/gateway-service.js
  webapp/src/App.js
  webapp/src/components/OptionsDropdown.js
  webapp/src/components/PersonalRanking.js
  webapp/src/components/Ranking.js
  webapp/src/components/UserAccount.js
Labels: ⚙ development, 🚀 improvement

#107 [DEV] Añadidas mejoras gráficas varias, barra lateral y mejora del navbar superior.
  webapp/public/FondoWichat_2.png
  webapp/src/App.js
  webapp/src/Login.css
  webapp/src/Register.css
  webapp/src/components/Faq.js
  webapp/src/components/Login.js
  webapp/src/components/OptionsDropdown.js
  webapp/src/components/Ranking.js
  webapp/src/components/Register.js
Labels: ⚙ development, ✨ visual enhancement

#108 LLM terminado
  gameservice/questions-service.js
  gatewayservice/gateway-service.js
  llmservice/chatbot.js
  webapp/backend/gameservice/questions-service.js
  webapp/package-lock.json
  webapp/package.json
  webapp/src/components/Chatbot.js
  webapp/src/components/Game.js
Labels: ⚙ development

#116 [DEV] Creados la mayoría de test de frontend
  package-lock.json
  package.json
  webapp/e2e/features/login-form.feature
  webapp/e2e/features/register-form.feature
  webapp/e2e/steps/login-form.steps.js
  webapp/e2e/steps/register-form.steps.js
  webapp/package-lock.json
  webapp/package.json
  webapp/src/App.test.js
  webapp/src/components/AddUser.test.js
  webapp/src/components/Faq.test.js
  webapp/src/components/Game.test.js
  webapp/src/components/Home.test.js
  webapp/src/components/Login.test.js
  webapp/src/components/OptionsDropdown.js
  webapp/src/components/OptionsDropdown.test.js
  webapp/src/components/PersonalRanking.test.js
  webapp/src/components/Ranking.test.js
  webapp/src/components/Register.test.js
Labels: ⚙ development, 👁️‍🗨️ ​test, 🚀 improvement

#114 Optimización de generación de preguntas
  .vscode/settings.json
  authservice/package-lock.json
  authservice/package.json
  docs/images/07_deployment_view-EN.png
  docs/images/07_deployment_view-EN.svg
  docs/package-lock.json
  docs/package.json
  docs/src/04_solution_strategy.adoc
  docs/src/07_deployment_view.adoc
  gameservice/data/questions-templates.json
  gameservice/models/question-model.js
  gameservice/package-lock.json
  gameservice/package.json
  gameservice/questions-service.js
  gameservice/tasks/preload-questions.js
  gameservice/util.js
  gatewayservice/package-lock.json
  gatewayservice/package.json
  llmservice/package-lock.json
  llmservice/package.json
  userservice/package-lock.json
  userservice/package.json
  webapp/package-lock.json
  webapp/package.json
Labels: 💡 enhancement, ⚙ development, 🚀 improvement

#124 [DEV] Tests e2e de Register arreglados y tests de Home hechos
  webapp/e2e/features/chatbot.feature
  webapp/e2e/features/home-form.feature
  webapp/e2e/steps/chatbot.steps.js
  webapp/e2e/steps/home-form.steps.js
  webapp/e2e/steps/register-form.steps.js
  webapp/package-lock.json
Labels: ⚙ development, 👁️‍🗨️ ​test

#132 Coverage Tests (Game)
  webapp/src/components/Game.test.js
Labels: 🚀 improvement

#137 [DOC] Revisión y arreglos de la documentación
  docs/src/06_runtime_view.adoc
  docs/src/08_concepts.adoc
Labels: 📄 documentation
