Repository Arquisoft/wichat_es1c, pull requests merged in 2025-04, with the labels that each got.

#158 [DEV] Cambios al NavBar para añadir animaciones y añadido contador de preguntas a Game.js
  webapp/src/components/Game.js
  webapp/src/components/OptionsDropdown.js
Labels: ⚙ development, ✨ visual enhancement

#169 [DEV] Prototipo de funcionalidad de confirmación de contraseña y de edición de usuario
  package-lock.json
  webapp/src/components/Register.js
  webapp/src/components/Register.test.js
  webapp/src/components/UserAccount.js
Labels: ⚙ development

#173 [STYLE] CSS de Ranking y UserAccount
  webapp/src/components/Ranking.js
  webapp/src/components/UserAccount.js
Labels: ✨ visual enhancement

#174 [STYLE] Añadidos iconos, degradado y quitado el botón de volver a inicio de las FAQ
  webapp/src/components/Faq.js
  webapp/src/components/OptionsDropdown.js
  webapp/src/components/PersonalRanking.js
Labels: ✨ visual enhancement

#179 [TEST] Hechos algunos tests de coverage.
  webapp/src/components/AdminMenu.test.js
  webapp/src/components/Game.test.js
  webapp/src/components/OptionsDropdown.js
  webapp/src/components/UserAccount.js
  webapp/src/components/UserAccount.test.js
Labels: 👁️‍🗨️ ​test

#182 [TEST] Tests extra de game
  webapp/src/components/AdminMenu.test.js
  webapp/src/components/Faq.test.js
  webapp/src/components/Game.test.js
  webapp/src/components/UserAccount.test.js
Labels: 👁️‍🗨️ ​test

#187 [TEST] Más tests para ampliar el coverage
  webapp/src/components/Chatbot.test.js
  webapp/src/components/Home.test.js
  webapp/src/components/UserAccount.test.js
Labels: 👁️‍🗨️ ​test

#198 Revisión y actualización de la documentación.
  docs/index.adoc
  docs/src/01_introduction_and_goals.adoc
  docs/src/03_context_and_scope.adoc
  docs/src/05_building_block_view.adoc
  docs/src/06_runtime_view.adoc
  docs/src/07_deployment_view.adoc
  docs/src/08_concepts.adoc
  docs/src/10_quality_requirements.adoc
  docs/src/11_technical_risks.adoc
  docs/src/12_glossary.adoc
  docs/src/12_tests.adoc
  docs/src/13_glossary.adoc
  gameservice/questions-service.js
Labels: 📄 documentation

#202 [DOC] Cambios a los puntos 8 y 10 de la documentación
  docs/src/08_concepts.adoc
  docs/src/10_quality_requirements.adoc
Labels: 📄 documentation

#203 [DOC] Actualización documentación apartado 02, 04 y 12 (tests)
  docs/src/02_architecture_constraints.adoc
  docs/src/04_solution_strategy.adoc
  docs/src/12_tests.adoc
Labels: 📄 documentation

#207 [TEST] Acabados los test de e2e
  webapp/e2e/steps/faq.steps.js
  webapp/e2e/steps/game-enter.steps.js
  webapp/e2e/steps/logout.steps.js
  webapp/src/components/OptionsDropdown.js
Labels: 👁️‍🗨️ ​test

#209 Test E2E autodesplegado
  docs/images/10-árbol.png
  docs/src/01_introduction_and_goals.adoc
  docs/src/10_quality_requirements.adoc
  docs/src/12_tests.adoc
  package-lock.json
  package.json
  webapp/e2e/addTestUser.js
  webapp/e2e/features/logout.feature
  webapp/e2e/steps/logout.steps.js
  webapp/e2e/test-environment-setup.js
  webapp/load_tests/users10during10sec/LoadApp.scala
  webapp/load_tests/users10during10sec/Login.scala
  webapp/load_tests/users10during10sec/LoginAndNav.scala
  webapp/load_tests/users10during10sec/LoginAndPlay.scala
  webapp/load_tests/users1during10sec/LoadApp.scala
  webapp/load_tests/users1during10sec/Login.scala
  webapp/load_tests/users1during10sec/LoginAndNav.scala
  webapp/load_tests/users1during10sec/LoginAndPlay.scala
  webapp/load_tests/users3during10sec/LoadApp.scala
  webapp/load_tests/users3during10sec/Login.scala
  webapp/load_tests/users3during10sec/LoginAndNav.scala
  webapp/load_tests/users3during10sec/LoginAndPlay.scala
  webapp/package-lock.json
  webapp/package.json
Labels: ⚙ development
